import type { ToolCategory, ToolDefinition } from "./types";

function tool(
  partial: Omit<ToolDefinition, "timeoutMs" | "errorBehavior"> & {
    timeoutMs?: number;
    errorBehavior?: ToolDefinition["errorBehavior"];
  },
): ToolDefinition {
  return {
    timeoutMs: partial.timeoutMs ?? 30_000,
    errorBehavior: partial.errorBehavior ?? "return",
    ...partial,
  };
}

export const TOOLS: readonly ToolDefinition[] = [
  tool({
    id: "token-data",
    name: "Token Data",
    description: "Fetch on-chain and market metadata for a Solana token mint.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "token-data",
    inputHint: "{ mint: string }",
    outputHint: "Token metadata, supply, and market snapshot",
  }),
  tool({
    id: "token-safety",
    name: "Token Safety Scan",
    description: "Run safety heuristics: mint authority, freeze, honeypot signals.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "token-safety",
    inputHint: "{ mint: string }",
    outputHint: "Safety score and risk flags",
  }),
  tool({
    id: "og-scan-token",
    name: "OG Token Scan",
    description: "Deep OG intelligence scan for a token including social and dev signals.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "og-scan-token",
    timeoutMs: 45_000,
    inputHint: "{ mint: string }",
    outputHint: "OG scan report with risk and opportunity tags",
  }),
  tool({
    id: "og-wallet",
    name: "OG Wallet Scan",
    description: "Analyze wallet holdings, history, and behavioral patterns.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "og-wallet",
    inputHint: "{ address: string }",
    outputHint: "Wallet profile, PnL hints, and activity summary",
  }),
  tool({
    id: "og-holders",
    name: "OG Holders",
    description: "Holder distribution, concentration, and smart-money overlap.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "og-holders",
    inputHint: "{ mint: string, limit?: number }",
    outputHint: "Top holders and concentration metrics",
  }),
  tool({
    id: "ogdex-intel",
    name: "OGDEX Intel",
    description: "Legacy OGDEX market intelligence for tokens and pairs.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "ogdex-intel",
    inputHint: "{ mint: string }",
    outputHint: "OGDEX intel payload",
  }),
  tool({
    id: "ogdex-intel-v2",
    name: "OGDEX Intel v2",
    description: "Enhanced OGDEX intelligence with richer liquidity and flow data.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "ogdex-intel-v2",
    timeoutMs: 45_000,
    inputHint: "{ mint: string }",
    outputHint: "OGDEX v2 structured intel",
  }),
  tool({
    id: "ogdex-xray",
    name: "OGDEX X-Ray",
    description: "X-ray style breakdown of token mechanics, flows, and anomalies.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "ogdex-xray",
    timeoutMs: 45_000,
    inputHint: "{ mint: string }",
    outputHint: "X-ray diagnostics and anomaly list",
  }),
  tool({
    id: "ogdex-firstbuyer",
    name: "OGDEX First Buyer",
    description: "Identify and profile early buyers and sniper wallets.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "ogdex-firstbuyer",
    inputHint: "{ mint: string }",
    outputHint: "First buyer wallet list with timestamps",
  }),
  tool({
    id: "pnl-scan",
    name: "PnL Scan",
    description: "Scan realized and unrealized PnL for a wallet or token pair.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "pnl-scan",
    inputHint: "{ wallet?: string, mint?: string }",
    outputHint: "PnL breakdown and trade history summary",
  }),
  tool({
    id: "unified-intelligence",
    name: "Unified Intelligence",
    description: "Aggregate multi-source intelligence into a single briefing.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "unified-intelligence",
    timeoutMs: 60_000,
    inputHint: "{ mint?: string, wallet?: string, query?: string }",
    outputHint: "Unified intel bundle",
  }),
  tool({
    id: "enhanced-intelligence",
    name: "Enhanced Intelligence",
    description: "Deep enhanced intel pass with AI-enriched summaries.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "enhanced-intelligence",
    timeoutMs: 60_000,
    inputHint: "{ mint?: string, wallet?: string }",
    outputHint: "Enhanced intel with narrative summary",
  }),
  tool({
    id: "ai-analyzer",
    name: "AI Analyzer",
    description: "LLM-powered analysis over structured market and on-chain inputs.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "ai-analyzer",
    timeoutMs: 60_000,
    inputHint: "{ subject: string, context?: Record<string, unknown> }",
    outputHint: "AI analysis text and structured findings",
  }),
  tool({
    id: "birdseye-analytics",
    name: "Birdseye Analytics",
    description: "Macro and sector analytics across Solana markets.",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "birdseye-analytics",
    inputHint: "{ scope?: string, timeframe?: string }",
    outputHint: "Market analytics dashboard data",
  }),
  tool({
    id: "solana-tracker",
    name: "Solana Tracker",
    description: "Track Solana network, program, or wallet activity streams.",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "solana-tracker",
    inputHint: "{ target: string, type?: 'wallet' | 'mint' | 'program' }",
    outputHint: "Activity feed and tracker state",
  }),
  tool({
    id: "oxw-token-scan",
    name: "OXW Token Scan",
    description: "OrbitX wallet-native token scan with safety and liquidity checks.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "oxw-token-scan",
    inputHint: "{ mint: string }",
    outputHint: "OXW scan results",
  }),
  tool({
    id: "jupiter-quote",
    name: "Jupiter Quote",
    description: "Fetch a swap quote via Jupiter without executing a trade.",
    category: "trade",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "jupiter-quote",
    inputHint: "{ inputMint: string, outputMint: string, amount: string, slippageBps?: number }",
    outputHint: "Quote route, price impact, and fees",
  }),
  tool({
    id: "jupiter-price",
    name: "Jupiter Price",
    description: "Current Jupiter-derived prices for token mints.",
    category: "trade",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "jupiter-price",
    inputHint: "{ mints: string[] }",
    outputHint: "Price map by mint",
  }),
  tool({
    id: "jupiter-tokens",
    name: "Jupiter Tokens",
    description: "Search and list Jupiter-supported tokens.",
    category: "trade",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "jupiter-tokens",
    inputHint: "{ query?: string }",
    outputHint: "Token list with mint addresses",
  }),
  tool({
    id: "jupiter-swap",
    name: "Jupiter Swap",
    description: "Build a swap transaction for wallet signing. Does not broadcast until user approves.",
    category: "trade",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "jupiter-swap",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ quoteResponse: unknown, userPublicKey: string }",
    outputHint: "Unsigned swap transaction for wallet sign",
  }),
  tool({
    id: "jupiter-order",
    name: "Jupiter Limit Order",
    description: "Create or manage a Jupiter limit order. Requires explicit user confirmation.",
    category: "trade",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "jupiter-order",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ orderParams: Record<string, unknown> }",
    outputHint: "Order payload for wallet sign or order status",
  }),
  tool({
    id: "alerts",
    name: "Alerts",
    description: "Create, update, or list price and wallet alerts.",
    category: "monitor",
    side: "write",
    permission: "limit",
    confirmationRequired: false,
    backend: "alerts",
    inputHint: "{ action: 'create' | 'list' | 'delete', alert?: Record<string, unknown> }",
    outputHint: "Alert record or alert list",
  }),
  tool({
    id: "send-push",
    name: "Send Push",
    description: "Send a push notification to the authenticated user device.",
    category: "monitor",
    side: "write",
    permission: "limit",
    confirmationRequired: false,
    backend: "send-push",
    inputHint: "{ title: string, body: string, data?: Record<string, unknown> }",
    outputHint: "Delivery status",
  }),
  tool({
    id: "post-to-x",
    name: "Post to X",
    description: "Compose and post content to X on behalf of the user.",
    category: "social",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "post-to-x",
    errorBehavior: "throw",
    inputHint: "{ text: string, mediaUrls?: string[] }",
    outputHint: "Post id and permalink",
  }),
  tool({
    id: "x-poster",
    name: "X Poster",
    description: "Schedule or publish formatted X posts with OrbitX templates.",
    category: "social",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "x-poster",
    errorBehavior: "throw",
    inputHint: "{ template: string, variables: Record<string, unknown> }",
    outputHint: "Scheduled or published post metadata",
  }),
  tool({
    id: "wallet-manager",
    name: "Wallet Manager",
    description: "Read wallet balances, token accounts, and connection state.",
    category: "orbitx",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "wallet-manager",
    inputHint: "{ action: 'balance' | 'tokens' | 'status' }",
    outputHint: "Wallet state and holdings",
  }),
  tool({
    id: "launch-coin",
    name: "Launch Coin",
    description: "Draft a pump.fun / OrbitX token launch. Returns a sign/open preview — never broadcasts.",
    category: "create",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "launch-coin",
    inputHint: "{ name: string, symbol: string, supply?: string, description?: string }",
    outputHint: "Launch draft, pump.fun create URL, and sign checklist",
  }),
  tool({
    id: "nft-mint",
    name: "Mint NFT",
    description: "Draft a Metaplex NFT mint. Returns a sign/open preview — never mints until they sign.",
    category: "create",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "nft-mint",
    inputHint: "{ name: string, symbol?: string, description?: string }",
    outputHint: "NFT mint draft and wallet-sign checklist",
  }),
  tool({
    id: "nft-execute-sale",
    name: "NFT Execute Sale",
    description: "Build an NFT sale or listing transaction for wallet signing.",
    category: "create",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "nft-execute-sale",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ mint: string, price: number, marketplace?: string }",
    outputHint: "Unsigned sale transaction",
  }),
  tool({
    id: "og-report-pdf",
    name: "OG Report PDF",
    description: "Generate a downloadable PDF research report for a token or wallet.",
    category: "create",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "og-report-pdf",
    timeoutMs: 90_000,
    inputHint: "{ subject: 'token' | 'wallet', id: string }",
    outputHint: "PDF URL and report metadata",
  }),
  tool({
    id: "news-fetcher",
    name: "News Fetcher",
    description: "Fetch crypto and Solana news relevant to a token, sector, or query.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "news-fetcher",
    inputHint: "{ query?: string, mint?: string }",
    outputHint: "News articles with sources and timestamps",
  }),
  tool({
    id: "track-record",
    name: "Track Record",
    description: "Historical performance and call accuracy for signals or agents.",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "track-record",
    inputHint: "{ entityId?: string, timeframe?: string }",
    outputHint: "Track record stats and history",
  }),
  tool({
    id: "migration-watch",
    name: "Migration Watch",
    description: "Monitor token migration events across launchpads and AMMs.",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "migration-watch",
    inputHint: "{ mint?: string }",
    outputHint: "Migration status and timeline",
  }),
  tool({
    id: "pumpfun-migrations",
    name: "Pump.fun Migrations",
    description: "Track Pump.fun bonding-curve migrations to Raydium and related pools.",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "pumpfun-migrations",
    inputHint: "{ mint?: string, status?: string }",
    outputHint: "Pump.fun migration list or detail",
  }),
] as const;

const TOOL_MAP = new Map<string, ToolDefinition>(
  TOOLS.map((t) => [t.id, t]),
);

export function getTool(id: string): ToolDefinition | undefined {
  return TOOL_MAP.get(id);
}

export function toolsByCategory(
  category?: ToolCategory,
): ToolDefinition[] {
  if (!category) {
    return [...TOOLS];
  }
  return TOOLS.filter((t) => t.category === category);
}

export function writeTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.side === "write");
}

export function readTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.side === "read");
}

export function toolsRequiringConfirmation(): ToolDefinition[] {
  return TOOLS.filter((t) => t.confirmationRequired);
}

export type { ToolDefinition };
