import type { ToolCategory, ToolDefinition } from "./types";

function tool(
  partial: Omit<ToolDefinition, "timeoutMs" | "errorBehavior"> & {
    timeoutMs?: number;
    errorBehavior?: ToolDefinition["errorBehavior"];
  },
): ToolDefinition {
  return {
    timeoutMs: partial.timeoutMs ?? 30_000,
    errorBehavior: partial.errorBehavior ?? "return",
    ...partial,
  };
}

export const TOOLS: readonly ToolDefinition[] = [
  tool({
    id: "token-data",
    name: "Token Data",
    description: "Fetch on-chain and market metadata for a Solana token mint.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "token-data",
    inputHint: "{ mint: string }",
    outputHint: "Token metadata, supply, and market snapshot",
  }),
  tool({
    id: "token-safety",
    name: "Token Safety Scan",
    description: "Run safety heuristics: mint authority, freeze, honeypot signals.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "token-safety",
    inputHint: "{ mint: string }",
    outputHint: "Safety score and risk flags",
  }),
  tool({
    id: "og-scan-token",
    name: "OG Token Scan",
    description: "Deep OG intelligence scan for a token including social and dev signals.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "og-scan-token",
    timeoutMs: 45_000,
    inputHint: "{ mint: string }",
    outputHint: "OG scan report with risk and opportunity tags",
  }),
  tool({
    id: "og-wallet",
    name: "OG Wallet Scan",
    description: "Analyze wallet holdings, history, and behavioral patterns.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "og-wallet",
    inputHint: "{ address: string }",
    outputHint: "Wallet profile, PnL hints, and activity summary",
  }),
  tool({
    id: "og-holders",
    name: "OG Holders",
    description: "Holder distribution, concentration, and smart-money overlap.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "og-holders",
    inputHint: "{ mint: string, limit?: number }",
    outputHint: "Top holders and concentration metrics",
  }),
  tool({
    id: "ogdex-intel",
    name: "OGDEX Intel",
    description: "Legacy OGDEX market intelligence for tokens and pairs.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "ogdex-intel",
    inputHint: "{ mint: string }",
    outputHint: "OGDEX intel payload",
  }),
  tool({
    id: "ogdex-intel-v2",
    name: "OGDEX Intel v2",
    description: "Enhanced OGDEX intelligence with richer liquidity and flow data.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "ogdex-intel-v2",
    timeoutMs: 45_000,
    inputHint: "{ mint: string }",
    outputHint: "OGDEX v2 structured intel",
  }),
  tool({
    id: "ogdex-xray",
    name: "OGDEX X-Ray",
    description: "X-ray style breakdown of token mechanics, flows, and anomalies.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "ogdex-xray",
    timeoutMs: 45_000,
    inputHint: "{ mint: string }",
    outputHint: "X-ray diagnostics and anomaly list",
  }),
  tool({
    id: "ogdex-firstbuyer",
    name: "OGDEX First Buyer",
    description: "Identify and profile early buyers and sniper wallets.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "ogdex-firstbuyer",
    inputHint: "{ mint: string }",
    outputHint: "First buyer wallet list with timestamps",
  }),
  tool({
    id: "pnl-scan",
    name: "PnL Scan",
    description: "Scan realized and unrealized PnL for a wallet or token pair.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "pnl-scan",
    inputHint: "{ wallet?: string, mint?: string }",
    outputHint: "PnL breakdown and trade history summary",
  }),
  tool({
    id: "unified-intelligence",
    name: "Unified Intelligence",
    description: "Aggregate multi-source intelligence into a single briefing.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "unified-intelligence",
    timeoutMs: 60_000,
    inputHint: "{ mint?: string, wallet?: string, query?: string }",
    outputHint: "Unified intel bundle",
  }),
  tool({
    id: "enhanced-intelligence",
    name: "Enhanced Intelligence",
    description: "Deep enhanced intel pass with AI-enriched summaries.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "enhanced-intelligence",
    timeoutMs: 60_000,
    inputHint: "{ mint?: string, wallet?: string }",
    outputHint: "Enhanced intel with narrative summary",
  }),
  tool({
    id: "ai-analyzer",
    name: "AI Analyzer",
    description: "LLM-powered analysis over structured market and on-chain inputs.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "ai-analyzer",
    timeoutMs: 60_000,
    inputHint: "{ subject: string, context?: Record<string, unknown> }",
    outputHint: "AI analysis text and structured findings",
  }),
  tool({
    id: "birdseye-analytics",
    name: "Birdseye Analytics",
    description: "Macro and sector analytics across Solana markets.",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "birdseye-analytics",
    inputHint: "{ scope?: string, timeframe?: string }",
    outputHint: "Market analytics dashboard data",
  }),
  tool({
    id: "solana-tracker",
    name: "Solana Tracker",
    description: "Track Solana network, program, or wallet activity streams.",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "solana-tracker",
    inputHint: "{ target: string, type?: 'wallet' | 'mint' | 'program' }",
    outputHint: "Activity feed and tracker state",
  }),
  tool({
    id: "oxw-token-scan",
    name: "OXW Token Scan",
    description: "OrbitX wallet-native token scan with safety and liquidity checks.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "oxw-token-scan",
    inputHint: "{ mint: string }",
    outputHint: "OXW scan results",
  }),
  tool({
    id: "jupiter-quote",
    name: "Jupiter Quote",
    description: "Fetch a swap quote via Jupiter without executing a trade.",
    category: "trade",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "jupiter-quote",
    inputHint: "{ inputMint: string, outputMint: string, amount: string, slippageBps?: number }",
    outputHint: "Quote route, price impact, and fees",
  }),
  tool({
    id: "jupiter-price",
    name: "Jupiter Price",
    description: "Current Jupiter-derived prices for token mints.",
    category: "trade",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "jupiter-price",
    inputHint: "{ mints: string[] }",
    outputHint: "Price map by mint",
  }),
  tool({
    id: "jupiter-tokens",
    name: "Jupiter Tokens",
    description: "Search and list Jupiter-supported tokens.",
    category: "trade",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "jupiter-tokens",
    inputHint: "{ query?: string }",
    outputHint: "Token list with mint addresses",
  }),
  tool({
    id: "jupiter-swap",
    name: "Jupiter Swap",
    description: "Build a swap transaction for wallet signing. Does not broadcast until user approves.",
    category: "trade",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "jupiter-swap",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ quoteResponse: unknown, userPublicKey: string }",
    outputHint: "Unsigned swap transaction for wallet sign",
  }),
  tool({
    id: "jupiter-order",
    name: "Jupiter Limit Order",
    description: "Create or manage a Jupiter limit order. Requires explicit user confirmation.",
    category: "trade",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "jupiter-order",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ orderParams: Record<string, unknown> }",
    outputHint: "Order payload for wallet sign or order status",
  }),
  tool({
    id: "alerts",
    name: "Alerts",
    description: "Create, update, or list price and wallet alerts.",
    category: "monitor",
    side: "write",
    permission: "limit",
    confirmationRequired: false,
    backend: "alerts",
    inputHint: "{ action: 'create' | 'list' | 'delete', alert?: Record<string, unknown> }",
    outputHint: "Alert record or alert list",
  }),
  tool({
    id: "send-push",
    name: "Send Push",
    description: "Send a push notification to the authenticated user device.",
    category: "monitor",
    side: "write",
    permission: "limit",
    confirmationRequired: false,
    backend: "send-push",
    inputHint: "{ title: string, body: string, data?: Record<string, unknown> }",
    outputHint: "Delivery status",
  }),
  tool({
    id: "post-to-x",
    name: "Post to X",
    description: "Compose and post content to X on behalf of the user.",
    category: "social",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "post-to-x",
    errorBehavior: "throw",
    inputHint: "{ text: string, mediaUrls?: string[] }",
    outputHint: "Post id and permalink",
  }),
  tool({
    id: "x-poster",
    name: "X Poster",
    description: "Schedule or publish formatted X posts with OrbitX templates.",
    category: "social",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "x-poster",
    errorBehavior: "throw",
    inputHint: "{ template: string, variables: Record<string, unknown> }",
    outputHint: "Scheduled or published post metadata",
  }),
  tool({
    id: "wallet-manager",
    name: "Wallet Manager",
    description: "Read wallet balances, token accounts, and connection state.",
    category: "orbitx",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "wallet-manager",
    inputHint: "{ action: 'balance' | 'tokens' | 'status' }",
    outputHint: "Wallet state and holdings",
  }),
  tool({
    id: "launch-coin",
    name: "Launch Coin",
    description: "Draft a pump.fun / OrbitX token launch. Returns a sign/open preview — never broadcasts.",
    category: "create",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "launch-coin",
    inputHint: "{ name: string, symbol: string, supply?: string, description?: string }",
    outputHint: "Launch draft, pump.fun create URL, and sign checklist",
  }),
  tool({
    id: "nft-mint",
    name: "Mint NFT",
    description: "Draft a Metaplex NFT mint. Returns a sign/open preview — never mints until they sign.",
    category: "create",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "nft-mint",
    inputHint: "{ name: string, symbol?: string, description?: string }",
    outputHint: "NFT mint draft and wallet-sign checklist",
  }),
  tool({
    id: "nft-execute-sale",
    name: "NFT Execute Sale",
    description: "Build an NFT sale or listing transaction for wallet signing.",
    category: "create",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "nft-execute-sale",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ mint: string, price: number, marketplace?: string }",
    outputHint: "Unsigned sale transaction",
  }),
  tool({
    id: "og-report-pdf",
    name: "OG Report PDF",
    description: "Generate a downloadable PDF research report for a token or wallet.",
    category: "create",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "og-report-pdf",
    timeoutMs: 90_000,
    inputHint: "{ subject: 'token' | 'wallet', id: string }",
    outputHint: "PDF URL and report metadata",
  }),
  tool({
    id: "news-fetcher",
    name: "News Fetcher",
    description: "Fetch crypto and Solana news relevant to a token, sector, or query.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "news-fetcher",
    inputHint: "{ query?: string, mint?: string }",
    outputHint: "News articles with sources and timestamps",
  }),
  tool({
    id: "track-record",
    name: "Track Record",
    description: "Historical performance and call accuracy for signals or agents.",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "track-record",
    inputHint: "{ entityId?: string, timeframe?: string }",
    outputHint: "Track record stats and history",
  }),
  tool({
    id: "migration-watch",
    name: "Migration Watch",
    description: "Monitor token migration events across launchpads and AMMs.",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "migration-watch",
    inputHint: "{ mint?: string }",
    outputHint: "Migration status and timeline",
  }),
  tool({
    id: "pumpfun-migrations",
    name: "Pump.fun Migrations",
    description: "Track Pump.fun bonding-curve migrations to Raydium and related pools.",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "pumpfun-migrations",
    inputHint: "{ mint?: string, status?: string }",
    outputHint: "Pump.fun migration list or detail",
  }),

  // ── Charting & technicals ────────────────────────────────────────────
  tool({
    id: "chart-data",
    name: "Chart Data",
    description: "OHLCV candles for a token across timeframes for charting and TA.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "chart-data",
    inputHint: "{ mint: string, timeframe?: '1m'|'5m'|'1h'|'4h'|'1d' }",
    outputHint: "OHLCV candle series",
  }),
  tool({
    id: "technical-indicators",
    name: "Technical Indicators",
    description: "Compute RSI, MACD, EMA, Bollinger Bands, and VWAP for a token.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "technical-indicators",
    inputHint: "{ mint: string, indicators?: string[], timeframe?: string }",
    outputHint: "Indicator values and signals",
  }),
  tool({
    id: "candle-patterns",
    name: "Candle Patterns",
    description: "Detect candlestick and chart patterns (engulfing, doji, breakouts).",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "candle-patterns",
    inputHint: "{ mint: string, timeframe?: string }",
    outputHint: "Detected patterns with confidence",
  }),
  tool({
    id: "volume-profile",
    name: "Volume Profile",
    description: "Volume-by-price distribution, value area, and point of control.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "volume-profile",
    inputHint: "{ mint: string, timeframe?: string }",
    outputHint: "Volume profile and key levels",
  }),
  tool({
    id: "support-resistance",
    name: "Support & Resistance",
    description: "Identify horizontal support/resistance and liquidity zones.",
    category: "intelligence",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "support-resistance",
    inputHint: "{ mint: string, timeframe?: string }",
    outputHint: "Support/resistance levels",
  }),
  tool({
    id: "correlation-matrix",
    name: "Correlation Matrix",
    description: "Cross-asset correlation between tokens and majors (SOL, BTC).",
    category: "monitor",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "correlation-matrix",
    inputHint: "{ mints: string[], timeframe?: string }",
    outputHint: "Correlation coefficients matrix",
  }),

  // ── DeFi: staking, lending, LP, perps, bridge ────────────────────────
  tool({
    id: "yield-scan",
    name: "Yield Scan",
    description: "Scan staking, lending, and LP yields across Solana protocols.",
    category: "defi",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "yield-scan",
    inputHint: "{ asset?: string, minApy?: number }",
    outputHint: "Ranked yield opportunities",
  }),
  tool({
    id: "stake-sol",
    name: "Stake SOL",
    description: "Prepare a SOL staking transaction (Marinade/Jito) for wallet signing.",
    category: "defi",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "stake-sol",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ amount: string, validator?: string }",
    outputHint: "Unsigned stake transaction",
  }),
  tool({
    id: "unstake-sol",
    name: "Unstake SOL",
    description: "Prepare an unstake/withdraw transaction for a stake account.",
    category: "defi",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "unstake-sol",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ stakeAccount: string, amount?: string }",
    outputHint: "Unsigned unstake transaction",
  }),
  tool({
    id: "lend-supply",
    name: "Lend Supply",
    description: "Prepare a supply/deposit into a lending market (Kamino/Solend).",
    category: "defi",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "lend-supply",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ market: string, mint: string, amount: string }",
    outputHint: "Unsigned supply transaction",
  }),
  tool({
    id: "lend-borrow",
    name: "Lend Borrow",
    description: "Prepare a borrow against supplied collateral. Requires confirmation.",
    category: "defi",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "lend-borrow",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ market: string, mint: string, amount: string }",
    outputHint: "Unsigned borrow transaction",
  }),
  tool({
    id: "lp-add",
    name: "Add Liquidity",
    description: "Prepare an add-liquidity transaction for an AMM pool.",
    category: "defi",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "lp-add",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ pool: string, amounts: Record<string, string> }",
    outputHint: "Unsigned add-liquidity transaction",
  }),
  tool({
    id: "lp-remove",
    name: "Remove Liquidity",
    description: "Prepare a remove-liquidity transaction for an AMM pool.",
    category: "defi",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "lp-remove",
    timeoutMs: 45_000,
    errorBehavior: "throw",
    inputHint: "{ pool: string, lpAmount: string }",
    outputHint: "Unsigned remove-liquidity transaction",
  }),
  tool({
    id: "perps-quote",
    name: "Perps Quote",
    description: "Quote a perpetual futures position (size, leverage, funding, liq price).",
    category: "defi",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "perps-quote",
    inputHint: "{ market: string, side: 'long'|'short', size: string, leverage?: number }",
    outputHint: "Perp quote with funding and liquidation price",
  }),
  tool({
    id: "bridge-quote",
    name: "Bridge Quote",
    description: "Quote a cross-chain bridge route and fees. No execution.",
    category: "defi",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "bridge-quote",
    inputHint: "{ fromChain: string, toChain: string, mint: string, amount: string }",
    outputHint: "Bridge route, fees, and ETA",
  }),

  // ── Wallet & portfolio ───────────────────────────────────────────────
  tool({
    id: "wallet-portfolio",
    name: "Wallet Portfolio",
    description: "Full portfolio snapshot: balances, allocations, and USD value.",
    category: "wallet",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "wallet-portfolio",
    inputHint: "{ address?: string }",
    outputHint: "Portfolio breakdown with allocations",
  }),
  tool({
    id: "wallet-approvals",
    name: "Token Approvals",
    description: "List token delegate approvals and potential drain risk.",
    category: "wallet",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "wallet-approvals",
    inputHint: "{ address?: string }",
    outputHint: "Approval list with risk flags",
  }),
  tool({
    id: "revoke-approval",
    name: "Revoke Approval",
    description: "Prepare a revoke transaction for a risky token delegate.",
    category: "wallet",
    side: "write",
    permission: "confirm",
    confirmationRequired: true,
    backend: "revoke-approval",
    errorBehavior: "throw",
    inputHint: "{ mint: string, delegate: string }",
    outputHint: "Unsigned revoke transaction",
  }),
  tool({
    id: "wallet-tax",
    name: "Wallet Tax Report",
    description: "Estimate realized gains/losses and generate a tax-style summary.",
    category: "wallet",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "wallet-tax",
    timeoutMs: 60_000,
    inputHint: "{ address?: string, year?: number }",
    outputHint: "Realized PnL and tax lot summary",
  }),
  tool({
    id: "airdrop-checker",
    name: "Airdrop Checker",
    description: "Check wallet eligibility across known Solana airdrops.",
    category: "wallet",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "airdrop-checker",
    inputHint: "{ address?: string }",
    outputHint: "Eligible airdrops and claim status",
  }),
  tool({
    id: "rebalance-plan",
    name: "Rebalance Plan",
    description: "Build a target-allocation rebalance plan as quote-only previews.",
    category: "wallet",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "rebalance-plan",
    inputHint: "{ targets: Record<string, number> }",
    outputHint: "Rebalance steps with quotes",
  }),

  // ── Social & sentiment ───────────────────────────────────────────────
  tool({
    id: "sentiment-scan",
    name: "Sentiment Scan",
    description: "Aggregate social sentiment for a token from public sources.",
    category: "social",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "sentiment-scan",
    inputHint: "{ mint?: string, query?: string }",
    outputHint: "Sentiment score and drivers",
  }),
  tool({
    id: "twitter-search",
    name: "Twitter/X Search",
    description: "Search recent X posts and mentions relevant to a token or query.",
    category: "social",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "twitter-search",
    inputHint: "{ query: string, limit?: number }",
    outputHint: "Recent posts with engagement",
  }),
  tool({
    id: "kol-mentions",
    name: "KOL Mentions",
    description: "Surface key-opinion-leader mentions and their historical accuracy.",
    category: "social",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "kol-mentions",
    inputHint: "{ mint?: string, handle?: string }",
    outputHint: "KOL mentions with track record",
  }),

  // ── Knowledge & education (no live writes) ───────────────────────────
  tool({
    id: "knowledge-base",
    name: "Knowledge Base",
    description: "Retrieve OrbitX/Solana knowledge base articles and how-tos.",
    category: "knowledge",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "knowledge-base",
    inputHint: "{ query: string }",
    outputHint: "Matching knowledge articles",
  }),
  tool({
    id: "glossary-lookup",
    name: "Glossary Lookup",
    description: "Define crypto, Solana, and DeFi terms in plain language.",
    category: "knowledge",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "glossary-lookup",
    inputHint: "{ term: string }",
    outputHint: "Term definition and context",
  }),
  tool({
    id: "protocol-explainer",
    name: "Protocol Explainer",
    description: "Explain how a Solana protocol works, its risks, and mechanics.",
    category: "knowledge",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "protocol-explainer",
    inputHint: "{ protocol: string }",
    outputHint: "Protocol overview and risks",
  }),
  tool({
    id: "strategy-library",
    name: "Strategy Library",
    description: "Browse rule-based trading and risk strategies with checklists.",
    category: "knowledge",
    side: "read",
    permission: "none",
    confirmationRequired: false,
    backend: "strategy-library",
    inputHint: "{ topic?: string }",
    outputHint: "Strategy templates and checklists",
  }),
] as const;

const TOOL_MAP = new Map<string, ToolDefinition>(
  TOOLS.map((t) => [t.id, t]),
);

export function getTool(id: string): ToolDefinition | undefined {
  return TOOL_MAP.get(id);
}

export function toolsByCategory(
  category?: ToolCategory,
): ToolDefinition[] {
  if (!category) {
    return [...TOOLS];
  }
  return TOOLS.filter((t) => t.category === category);
}

export function writeTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.side === "write");
}

export function readTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.side === "read");
}

export function toolsRequiringConfirmation(): ToolDefinition[] {
  return TOOLS.filter((t) => t.confirmationRequired);
}

export type { ToolDefinition };
