import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useMemo, useState } from "react";
import { colors } from "../theme";
import { createPartialTakeProfitLadder, createBuyLadder, type LadderOrder } from "../lib/limitLadder";

export function LimitLadder({currentMc=1000000,onPlace}:{currentMc?:number;onPlace?:(orders:LadderOrder[])=>void}){const [side,setSide]=useState<"sell"|"buy">("sell");const [percent,setPercent]=useState("25");const [allocation,setAllocation]=useState("10");const [orders,setOrders]=useState<LadderOrder[]>([]);const pct=Number(percent)||0;const alloc=Math.min(100,Math.max(0,Number(allocation)||0));const target=currentMc*(1+pct/100);const total=useMemo(()=>orders.reduce((s,o)=>s+o.allocationPct,0),[orders]);
const add=()=>{if(alloc<=0||total+alloc>100)return;const order:LadderOrder={id:`custom-${Date.now()}`,side,targetMc:Math.max(0,target),targetChangePct:pct,allocationPct:alloc,status:"pending"};setOrders(x=>[...x,order]);};
const preset=(kind:"tp"|"buy")=>{const created=kind==="tp"?createPartialTakeProfitLadder(currentMc):createBuyLadder(currentMc);setOrders(created);};
return <View style={styles.root}><View style={styles.head}><Text style={styles.title}>LIMIT LADDER</Text><Text style={styles.remaining}>{(100-total).toFixed(0)}% available</Text></View><View style={styles.tabs}><Pressable onPress={()=>setSide("sell")} style={[styles.tab,side==="sell"&&styles.active]}><Text style={styles.tabText}>SELL / TAKE PROFIT</Text></Pressable><Pressable onPress={()=>setSide("buy")} style={[styles.tab,side==="buy"&&styles.active]}><Text style={styles.tabText}>BUY / DCA</Text></Pressable></View><View style={styles.presetRow}><Pressable onPress={()=>preset("tp")} style={styles.preset}><Text style={styles.action}>10% @ +25/+50/+100/+200%</Text></Pressable><Pressable onPress={()=>preset("buy")} style={styles.preset}><Text style={styles.action}>10% @ -10/-20/-30%</Text></Pressable></View><View style={styles.inputs}><View style={styles.field}><Text style={styles.label}>MC CHANGE %</Text><TextInput value={percent} onChangeText={setPercent} keyboardType="numeric" style={styles.input}/></View><View style={styles.field}><Text style={styles.label}>HOLDINGS %</Text><TextInput value={allocation} onChangeText={setAllocation} keyboardType="numeric" style={styles.input}/></View></View><Text style={styles.preview}>TARGET MC  ${Math.round(target).toLocaleString()}</Text><Pressable style={styles.add} onPress={add}><Text style={styles.addText}>+ ADD {side.toUpperCase()} ORDER</Text></Pressable>{orders.map(o=><View key={o.id} style={styles.order}><Text style={styles.side}>{o.side.toUpperCase()}</Text><View style={styles.orderMain}><Text style={styles.mc}>${Math.round(o.targetMc).toLocaleString()}</Text><Text style={styles.muted}>{o.targetChangePct>=0?"+":""}{o.targetChangePct.toFixed(1)}% MC · {o.allocationPct}% holdings</Text></View><Text style={styles.pending}>PENDING</Text></View>)}<Pressable disabled={!orders.length} onPress={()=>onPlace?.(orders)} style={[styles.place,!orders.length&&styles.disabled]}><Text style={styles.placeText}>PLACE {orders.length} ORDERS</Text></Pressable></View>}
const styles=StyleSheet.create({root:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.hairline,borderRadius:16,padding:14,gap:10},head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:colors.frost,fontFamily:"Inter_600SemiBold",fontSize:11,letterSpacing:1.5},remaining:{color:colors.signal,fontSize:10},tabs:{flexDirection:"row",gap:6},tab:{flex:1,paddingVertical:9,borderRadius:8,backgroundColor:colors.ink,alignItems:"center"},active:{borderWidth:1,borderColor:colors.signal},tabText:{color:colors.mist,fontSize:9,fontFamily:"Inter_500Medium"},presetRow:{gap:6},preset:{padding:8,borderRadius:8,borderWidth:1,borderColor:colors.line},action:{color:colors.signal,fontSize:10},inputs:{flexDirection:"row",gap:8},field:{flex:1,gap:5},label:{color:colors.mute,fontSize:9},input:{color:colors.frost,backgroundColor:colors.ink,borderWidth:1,borderColor:colors.line,borderRadius:8,padding:9},preview:{color:colors.ice,fontFamily:"Inter_600SemiBold",fontSize:12},add:{borderWidth:1,borderColor:colors.signal,borderRadius:9,paddingVertical:10,alignItems:"center"},addText:{color:colors.signal,fontFamily:"Inter_600SemiBold",fontSize:11},order:{flexDirection:"row",alignItems:"center",gap:9,borderTopWidth:1,borderTopColor:colors.line,paddingTop:9},side:{color:colors.signal,fontSize:9,fontFamily:"Inter_600SemiBold",width:34},orderMain:{flex:1},mc:{color:colors.frost,fontFamily:"Inter_600SemiBold"},muted:{color:colors.mute,fontSize:9},pending:{color:colors.mute,fontSize:8},place:{backgroundColor:colors.signal,borderRadius:10,paddingVertical:12,alignItems:"center"},placeText:{color:colors.void,fontFamily:"Inter_600SemiBold",fontSize:11},disabled:{opacity:.35}});
